### ISSUE TITLE
exception thrown when no header and/or footer

### ISSUE THREAD

**Issue by mchlumsky** [mchlumsky/topshape#13]
* TopShape version: 0.2.0
* Python version:3.5
* Operating System: Fedora Linux 25

### Description

When app is created with no header and/or footer functions, a stacktrace is thrown:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "stacktop/venv3/lib/python3.5/site-packages/topshape-0.2.0-py3.5.egg/topshape/topshape.py", line 88, in run
    self.header = self._header_func()
TypeError: 'NoneType' object is not callable

### What I Did

app = TopShape.create_app(COLUMNS, body)
app.run()

**Comment by mchlumsky** [comment]
Header is now mandatory.

Footer is still optional.

**Comment by mchlumsky** [comment]
Fixed by #22
